name: taxi_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-366.0.dev <4.0.0'

dependencies:
  intl: ^0.18.1
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12
  google_fonts: ^5.1.0
  animator: ^3.0.1
  smooth_page_indicator: ^1.1.0
  country_pickers: ^2.0.0
  dotted_border: ^2.0.0+3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  http: ^1.1.0
  http_parser: ^4.0.2
  provider: ^6.0.3
  path_provider: ^2.0.14
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  flutter_local_notifications: ^16.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.1.1
  google_maps_flutter: ^2.1.7
  flutter_polyline_points: ^2.0.0
  velocity_x: ^4.1.1
  get: ^4.6.5
  google_nav_bar: ^5.0.6
  flutter_ringtone_player: ^3.2.0
  google_maps: ^6.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  assets:  
  - assets/
  - assets/images/
  - jsonFile/darkmapstyle.json
  - jsonFile/lightmapstyle.json
  - jsonFile/languagetext.json


  uses-material-design: true

  fonts:
    - family: myfonts
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf